"""Reader for compression_report.json files generated by compress.py."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import List

from ...domain.enums import ResultCategory, ResultSource
from ...domain.models import (
    CompressionMetrics,
    MetricRecord,
    ModelInfo,
    TimingMetrics,
)


class CompressionReportReader:
    """Adapter that reads ``compression_report.json`` files.

    These files are generated by compress.py and contain:
    - Original and compressed sizes
    - Compression ratio and savings percentage
    - Compression time
    - Number of Gaussians
    - Chunking information
    """

    # ── IDataSourceReader protocol ──────────────────────────────

    @property
    def source_type(self) -> ResultSource:
        return ResultSource.COMPRESSION_REPORT

    def supports(self, path: Path) -> bool:
        if not path.is_file():
            return False
        return path.name.lower() == "compression_report.json"

    def read(self, path: Path) -> List[MetricRecord]:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Extract technique name from parent directory path
        # e.g., compressed_output/balanced/ -> "balanced"
        parts = path.parts
        technique = "unknown"
        if "compressed_output" in parts:
            idx = parts.index("compressed_output")
            if idx + 1 < len(parts):
                technique = parts[idx + 1]

        # Extract scene name from model_path if available
        scene = self._extract_scene_name(data.get("model_path", ""))

        record = self._parse_report(data, technique, scene, path)
        return [record]

    # ── Internal helpers ────────────────────────────────────────

    @staticmethod
    def _extract_scene_name(model_path: str) -> str:
        """Extract scene name from model path.

        E.g., 'output/dynerf/coffee_martini' -> 'coffee_martini'
        """
        if not model_path:
            return ""
        parts = Path(model_path).parts
        if len(parts) > 0:
            return parts[-1]
        return ""

    @staticmethod
    def _make_id(technique: str, scene: str) -> str:
        raw = f"compression_report:{technique}:{scene}"
        return hashlib.md5(raw.encode()).hexdigest()[:12]

    def _parse_report(self, data: dict, technique: str, scene: str, path: Path) -> MetricRecord:
        """Parse a compression_report.json into a MetricRecord."""
        record_id = self._make_id(technique, scene)

        # Extract configuration file name for display
        config_file = data.get("config_file", "")
        config_name = Path(config_file).stem if config_file else technique

        return MetricRecord(
            id=record_id,
            source=ResultSource.COMPRESSION_REPORT,
            category=ResultCategory.COMPRESSION,
            name=f"{technique} ({scene})" if scene else technique,
            scene=scene,
            tags={
                "technique": technique,
                "config_file": config_file,
                "iteration": str(data.get("iteration", "")),
                "source_path": str(path),
            },
            compression_metrics=CompressionMetrics(
                original_size_bytes=data.get("original_size_bytes", 0),
                compressed_size_bytes=data.get("compressed_size_bytes", 0),
                compression_ratio=data.get("compression_ratio", 1.0),
                savings_pct=data.get("savings_pct", 0.0),
                num_chunks=data.get("num_chunks", 0),
            ),
            timing_metrics=TimingMetrics(
                compress_time_s=data.get("compression_time_s"),
            ),
            model_info=ModelInfo(
                num_gaussians_original=data.get("num_gaussians"),
                iteration=data.get("iteration"),
            ),
        )
