"""Reader for decompression_report.json files generated by decompress.py."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import List

from ...domain.enums import ResultCategory, ResultSource
from ...domain.models import (
    MetricRecord,
    ModelInfo,
    TimingMetrics,
)


class DecompressionReportReader:
    """Adapter that reads ``decompression_report.json`` files.

    These files are generated by decompress.py and contain:
    - Assembly, decode, and export timing
    - Number of Gaussians and frames
    - SH degree
    - Archive size
    """

    # ── IDataSourceReader protocol ──────────────────────────────

    @property
    def source_type(self) -> ResultSource:
        return ResultSource.DECOMPRESSION_REPORT

    def supports(self, path: Path) -> bool:
        if not path.is_file():
            return False
        return path.name.lower() == "decompression_report.json"

    def read(self, path: Path) -> List[MetricRecord]:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Extract technique name from parent directory path
        # e.g., decompressed_output/balanced/ -> "balanced"
        parts = path.parts
        technique = "unknown"
        if "decompressed_output" in parts:
            idx = parts.index("decompressed_output")
            if idx + 1 < len(parts):
                technique = parts[idx + 1]

        # Try to infer scene name from sibling directories or parent path
        scene = self._infer_scene_name(path, technique)

        record = self._parse_report(data, technique, scene, path)
        return [record]

    # ── Internal helpers ────────────────────────────────────────

    @staticmethod
    def _infer_scene_name(path: Path, technique: str) -> str:
        """Try to infer scene name from directory structure or naming patterns."""
        # Look for scene-specific subdirectories
        parent = path.parent
        if parent.name != technique:
            return parent.name
        return ""

    @staticmethod
    def _make_id(technique: str, scene: str) -> str:
        raw = f"decompression_report:{technique}:{scene}"
        return hashlib.md5(raw.encode()).hexdigest()[:12]

    def _parse_report(self, data: dict, technique: str, scene: str, path: Path) -> MetricRecord:
        """Parse a decompression_report.json into a MetricRecord."""
        record_id = self._make_id(technique, scene)

        # Calculate total decompression time
        assemble_time = data.get("assemble_time_s", 0.0)
        decode_time = data.get("decode_time_s", 0.0)
        export_time = data.get("export_time_s", 0.0)
        total_time = data.get("total_time_s", assemble_time + decode_time + export_time)

        return MetricRecord(
            id=record_id,
            source=ResultSource.DECOMPRESSION_REPORT,
            category=ResultCategory.DECOMPRESSION,
            name=f"{technique} ({scene})" if scene else technique,
            scene=scene,
            tags={
                "technique": technique,
                "num_frames": str(data.get("num_frames", "")),
                "assemble_time_s": str(assemble_time),
                "decode_time_s": str(decode_time),
                "export_time_s": str(export_time),
                "source_path": str(path),
            },
            timing_metrics=TimingMetrics(
                decompress_time_s=total_time,
                export_time_per_frame_s=export_time / data.get("num_frames", 1) if data.get("num_frames", 0) > 0 else None,
            ),
            model_info=ModelInfo(
                num_gaussians_compressed=data.get("num_gaussians"),
                sh_degree_compressed=data.get("sh_degree"),
            ),
        )
